# SPDX-License-Identifier: MPL-2.0
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install  then run ` lint` and ` test`.
# For more information see: https://github.com/denoland/setup-

name: 
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup 
        # uses: denoland/setup-@909cc5acb0135c37a79510dd77767e217930de55
        uses: denoland/setup-@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
        with:
          -version: v1.x
      # Uncomment this step to verify the use of ' fmt' on each commit.
      # - name: Verify formatting
      #   run:  fmt --check
      - name: Run linter
        run:  lint
      - name: Run tests
        run:  test -A
