# SPDX-License-Identifier: PMPL-1.0-or-later
defmodule DyadtBrain.Fleet.Reporter do
  @moduledoc """
  Reports dyadtbot results back to the fleet shared context and external systems.

  Output formats:
  - SARIF (for GitHub Security tab)
  - Fleet shared context JSON
  - PR comments (markdown)
  """

  @doc "Generate SARIF output from a dyadtbot report."
  def to_sarif(report) when is_map(report) do
    results =
      (report["results"] || [])
      |> Enum.flat_map(&sarif_results_for_claim/1)

    %{
      "$schema" => "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/main/sarif-2.1/schema/sarif-schema-2.1.0.json",
      "version" => "2.1.0",
      "runs" => [
        %{
          "tool" => %{
            "driver" => %{
              "name" => "dyadtbot",
              "version" => "0.1.0",
              "informationUri" => "https://gitlab.com/hyperpolymath/did-you-actually-do-that",
              "rules" => sarif_rules()
            }
          },
          "results" => results
        }
      ]
    }
  end

  @doc "Generate a markdown PR comment from a dyadtbot report."
  def to_pr_comment(report) when is_map(report) do
    total = report["total_claims"] || 0
    confirmed = report["confirmed"] || 0
    refuted = report["refuted"] || 0
    score = report["score"] || 0.0

    status_emoji =
      cond do
        refuted > 0 -> ":x:"
        confirmed == total and total > 0 -> ":white_check_mark:"
        true -> ":warning:"
      end

    header = "## #{status_emoji} DYADT Verification Report\n\n"

    summary = """
    | Metric | Value |
    |--------|-------|
    | Claims found | #{total} |
    | Confirmed | #{confirmed} |
    | Refuted | #{refuted} |
    | Score | #{Float.round(score * 100, 1)}% |
    """

    details =
      if refuted > 0 do
        refuted_claims =
          (report["results"] || [])
          |> Enum.filter(&(get_in(&1, ["verification", "final_verdict"]) == "Refuted"))
          |> Enum.map(fn r ->
            claim = r["claim"]["description"] || "?"
            "- **Refuted**: #{claim}"
          end)
          |> Enum.join("\n")

        "\n### Refuted Claims\n\n#{refuted_claims}\n"
      else
        ""
      end

    footer = "\n---\n*Generated by [dyadtbot](https://gitlab.com/hyperpolymath/did-you-actually-do-that)*\n"

    header <> summary <> details <> footer
  end

  @doc "Generate fleet shared context JSON."
  def to_fleet_context(report) when is_map(report) do
    %{
      "bot_id" => "dyadtbot",
      "repo" => report["repo"],
      "findings" => build_findings(report),
      "summary" => %{
        "total_claims" => report["total_claims"] || 0,
        "confirmed" => report["confirmed"] || 0,
        "refuted" => report["refuted"] || 0,
        "score" => report["score"] || 0.0
      },
      "timestamp" => report["generated_at"]
    }
  end

  # Private

  defp sarif_results_for_claim(result) do
    verification = result["verification"]
    claim = result["claim"]

    case verification do
      {:ok, report} when is_map(report) ->
        if report["final_verdict"] == "Refuted" do
          [
            %{
              "ruleId" => "dyadt/claim-refuted",
              "level" => "error",
              "message" => %{
                "text" => "Claim refuted: #{claim["description"] || "?"}"
              },
              "locations" => []
            }
          ]
        else
          []
        end

      _ ->
        []
    end
  end

  defp sarif_rules do
    [
      %{
        "id" => "dyadt/claim-refuted",
        "name" => "ClaimRefuted",
        "shortDescription" => %{"text" => "AI claim was refuted by verification"},
        "helpUri" => "https://gitlab.com/hyperpolymath/did-you-actually-do-that"
      },
      %{
        "id" => "dyadt/stub-detected",
        "name" => "StubDetected",
        "shortDescription" => %{"text" => "Stub or placeholder code detected"},
        "helpUri" => "https://gitlab.com/hyperpolymath/did-you-actually-do-that"
      },
      %{
        "id" => "dyadt/scope-reduced",
        "name" => "ScopeReduced",
        "shortDescription" => %{"text" => "Scope silently reduced from claimed work"},
        "helpUri" => "https://gitlab.com/hyperpolymath/did-you-actually-do-that"
      }
    ]
  end

  defp build_findings(report) do
    (report["results"] || [])
    |> Enum.filter(fn r ->
      v = r["verification"]
      is_tuple(v) and elem(v, 0) == :ok and elem(v, 1)["final_verdict"] == "Refuted"
    end)
    |> Enum.map(fn r ->
      %{
        "type" => "claim_refuted",
        "description" => r["claim"]["description"] || "?",
        "severity" => "high"
      }
    end)
  end

  defp get_in(nil, _keys), do: nil
  defp get_in(map, []), do: map

  defp get_in(map, [key | rest]) when is_map(map) do
    get_in(Map.get(map, key), rest)
  end

  defp get_in({:ok, map}, keys), do: get_in(map, keys)
  defp get_in(_, _), do: nil
end
